### ISSUE TITLE
Is it possible to have multiple configuration files in app?

### ISSUE THREAD

**Issue by vitt0re** [rwbutler/TypographyKit#4]
Is it possible to have multiple configuration files in app?
I'm using version 1.1.5 with iOS 11.4
I tried to assign new configuration plist file (with different name in resources) and tried do Typography.refresh() but it has no effect
The reason is to split configuration between several views keeping only necessary settings
Thanks

**Comment by rwbutler** [comment]
TypographyKit isn't designed to work with multiple configuration files but updating the configuration file and refreshing should work so I'll look to see what's going on here. It might help to understand what you're looking to achieve by having separate configuration files - is this so that you can reuse different color name / typography styles for different screens?
